### ISSUE TITLE
Creation of a handler which doesn't set a string as response content hangs the server

### ISSUE THREAD

**Issue by whimboo** [w3c/wptserve#105]
The following handler will cause the server to hang while delivering the page content:

> ```
>   def handler(request, response):
>         response.content = 1
>         return ()
> ```

This happens because a non-string value gets set as the content.

**Comment by wpt-issue-mover** [comment]
This issue has been moved to https://github.com/w3c/web-platform-tests/issues/8368; please continue all discussion there.
