### ISSUE TITLE
Add support to include files as data URLs

### ISSUE THREAD

**Issue by gsnedders** [w3c/wptserve#109]
Tests containing data URLs are horrible because data URLs are opaque strings. We should improve on this somehow, IMO by providing some feature to substitute in a file as a data URL with a given Content-Type and with a base64 flag.

**Comment by chayano** [comment]
Gueng.taro@gmail.com

**Comment by wpt-issue-mover** [comment]
This issue has been moved to https://github.com/w3c/web-platform-tests/issues/8370; please continue all discussion there.
