### ISSUE TITLE
Support HTTP/2

### ISSUE THREAD

**Issue by annevk** [w3c/wptserve#110]
It would be good to also have tests that go over HTTP/2. There are a couple of subtle differences with HTTP/1 and if HTTP/2 is on the rise it would be good to start covering it.

Differences I'm aware of:

* Header casing can matter in HTTP/1
* WebSocket only works in HTTP/1
* Chunked encoding is only in HTTP/1 (this will matter when Fetch gets "upload streams")

**Comment by gsnedders** [comment]
See also: #110.

**Comment by gsnedders** [comment]
See also: #80. I think realistically that's only ever going to get resolved by supporting HTTP/2.

**Comment by annevk** [comment]
Well, we need to test #80 without HTTP/2 as well ideally. We'd cover a lot less potential failure paths otherwise.

**Comment by wpt-issue-mover** [comment]
This issue has been moved to https://github.com/w3c/web-platform-tests/issues/8371; please continue all discussion there.
