### ISSUE TITLE
0x0B and 0x0C stripped from header values

### ISSUE THREAD

**Issue by annevk** [w3c/wptserve#111]
These are not HTTP whitespace. They should be preserved I think. Where is the header value parsing code?

**Comment by Ms2ger** [comment]
In some python standard library thing, I'm afraid :/

**Comment by jgraham** [comment]
Yeah it's not trivial to change, but maybe we want to move away from using the stdlib parts here in general, especially if we want to allow early responses and so on.

Is this affecting a test that you're writing right now?

**Comment by annevk** [comment]
Yes, this affects https://github.com/w3c/web-platform-tests/issues/4525.

**Comment by gsnedders** [comment]
Yeah, I'm increasingly in favour of moving away from it as well. We could possibly refactor stuff once we're away from that too…

**Comment by annevk** [comment]
What standard library are we using now? It seems we should file a bug there too if they strip 0x0B and 0x0C (if they use GitHub...).

**Comment by gsnedders** [comment]
@annevk unless you can make it out to be a security issue, it's almost certainly not getting fixed in Python 2.

**Comment by gsnedders** [comment]
(It seems to already have been fixed in Python 3.)

**Comment by annevk** [comment]
https://bugs.python.org/issue22233 was the issue. It's a little strange they don't consider the CR LF sequence a single newline though. I wonder if that leads to issues. Anyway, moving to Python 3 is not an option so I guess we'll have to fix this here.

**Comment by gsnedders** [comment]
Nah, that bug was only introduced in Python 3, but yes, would've broken this too!

https://github.com/python/cpython/commit/15a312f0238df6add3ca64e9934ab258e06a5006 is where the bug that breaks this in 2.7 was fixed in Python 3.

**Comment by wpt-issue-mover** [comment]
This issue has been moved to https://github.com/w3c/web-platform-tests/issues/8372; please continue all discussion there.
