### ISSUE TITLE
Trickled responses are cacheable

### ISSUE THREAD

**Issue by gsnedders** [w3c/wptserve#118]
With http://web-platform.test:8000/images/blue.png?pipe=trickle(d5) included as an image, Firefox will take 7s (as expected) to load initially; it will thereafter load instantly from cache. This is problematic. Trickled responses *must not* be cacheable.

**Comment by wpt-issue-mover** [comment]
This issue has been moved to https://github.com/w3c/web-platform-tests/issues/8375; please continue all discussion there.
