### ISSUE TITLE
Support different escaping for substitution pipe

### ISSUE THREAD

**Issue by zcorpan** [w3c/wptserve#28]
Currently .sub.html changes `&` to `&amp;` for `{{GET[foo]}}` which is nice if you use it in e.g. an attribute value, but less nice if you use it inside a `<script>`.

It would be nice to be able to ask for specific escaping rules for different contexts. At least for `{{GET[]}}` but possibly also for `{{headers[]}}`.

html: entity-escape `& " ' < >`
script-string: backslash-escape `\ " ' <!-- </script`

**Comment by wpt-issue-mover** [comment]
This issue has been moved to https://github.com/w3c/web-platform-tests/issues/8357; please continue all discussion there.
