### ISSUE TITLE
Endorse as a feature the possibility to change the document root while the server is running

### ISSUE THREAD

**Issue by andreieftimie** [w3c/wptserve#32]
There's an interesting behaviour that allows us to change the document root _while_ the server is running.

Once the server is running if you change `httpd.router.doc_root` the next request will use the new value as document root.

I would like to propose that this becomes a supported feature.
This is a web server created for running tests. Changing the document root without requiring a restart is a really nice feature.

**Comment by wpt-issue-mover** [comment]
This issue has been moved to https://github.com/w3c/web-platform-tests/issues/8358; please continue all discussion there.
