### ISSUE TITLE
.sub templating for optional keys

### ISSUE THREAD

**Issue by hillbrad** [w3c/wptserve#39]
Is there a graceful way to use .sub processing when a value may not exist?

The simplest possible example is:

foo.sub.txt contains the following:

bar on the GET string is "{{GET[bar]}}"

If I make a request for "foo.sub.txt?bar=baz", I get what I expect:

bar on the GET string is "baz"

But If I make a request for just "foo.sub.txt" (leaving bar undefined on the GET string), I get a KeyError and status code 500.  This seems rather fragile for a templating system.

is there a syntax to make it gracefully default to an empty string if a key doesn't existt?

**Comment by wpt-issue-mover** [comment]
This issue has been moved to https://github.com/w3c/web-platform-tests/issues/8360; please continue all discussion there.
