### ISSUE TITLE
Lack of output encoding creates unavoidable security issues for .sub files

### ISSUE THREAD

**Issue by hillbrad** [w3c/wptserve#41]
Template substitution is a nice way to avoid "active" content like .py or .php files where security errors can give server-side code execution, but without an encoding context it introduces unavoidable XSS and other injection issues into the .sub files.  (as compared to PHP where you can apply a sanitization function to data before including it into a page)

Consider  example.sub.js:

 var userData  = "{{GET[userData]}}";

I can GET /example.sub.js?%22%3B%20var%20evil%20%3D%20%22somethingBad

Which yields:

 var userData = ""; var evil = "somethingBad";

The same issue exists for .html, .sub.headers, etc...

It is probably necessary to add syntax and functionality to the template engine to describe the context into which the substitution will occur so that it can be properly escaped.

**Comment by wpt-issue-mover** [comment]
This issue has been moved to https://github.com/w3c/web-platform-tests/issues/8361; please continue all discussion there.
