### ISSUE TITLE
Accessing URLs with spaces included causes a 404 response

### ISSUE THREAD

**Issue by whimboo** [w3c/wptserve#74]
As I noticed today while working on https://github.com/mozilla/mozdownload/issues/368, wptserve fails in handling of URLs with spaces included. An example URL like this:

> http://127.0.0.1:8081/firefox/releases/23.0.1/win32/en-US/Firefox Setup 23.0.1.exe

will cause the following failure:

{"error": {"message": "", "code": 404}}

**Comment by jgraham** [comment]
This wfm with latest wptserve. How are you getting this? If it's from PyPI I think we are long overdue a release.

**Comment by whimboo** [comment]
Yes, I'm using version 1.3 from PyPI. And maybe this only happens to the file handler which is in use here. I could grab the latest state of wptserve from github and check, just to make sure this is not a problem anymore.

**Comment by whimboo** [comment]
Oh, I have seen that you already pushed a new release. I will check with that one first.

**Comment by whimboo** [comment]
Ok, I upgraded my virtualenv to wptserve 1.4 and the issue is fixed. I had a look at the PR history and found that this issue is actually a dupe of issue #69.
