### ISSUE TITLE
Class members for the WebTestHttpd class should be properties which access values via inner httpd instance

### ISSUE THREAD

**Issue by whimboo** [w3c/wptserve#76]
The WebTestHttpd class has not a private marked members like `router`. All those are getting forwarded to the inner `httpd` instance within the `__init__()` method. Customer code would be able to change the `router` value but without any affect. Instead `cls.httpd.router` would have to be updated.

As result this gives an inconsistency between class members and actually used values. Best here would be to make all those members properties which read/write the values from/to the inner `httpd` class instance.

**Comment by wpt-issue-mover** [comment]
This issue has been moved to https://github.com/w3c/web-platform-tests/issues/8364; please continue all discussion there.
